---
title: "Stability Validation"
author: "Sandesh Shrestha"
format: html
editor: visual
---

# Setup

```{r, message=FALSE, warning=FALSE}
#packages
library(dplyr)
library(tidyr)
library(readr)
library(sf)
library(ggplot2)
library(viridis)
library(ggthemes)
library(patchwork)
library(forcats)
```

```{r defining map theme}
mytheme_map <- theme_map() +
  theme(legend.position = "right",
        panel.background = element_rect(fill = "white",
                                        color = NA),
        plot.background = element_rect(fill = "white",
                                       color = NA),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)
        )

```


# Data Import

```{r yield}
yield_int <- read_sf("../Output/yield_interpolated.geojson")

yield_int
```
```{r terrain}
terrain_v <-read_sf("../Output/terrain_v.geojson")
terrain_v
```

```{r soil eca}
eca_v <-  read_sf("../Output/eca_v.geojson")
eca_v
```
```{r}
boundary <- read_sf("../Data/boundary/DR1 boundary.shp") %>% 
  st_transform(crs = 6345)

boundary
```
# Combining all the data together

```{r}
all_v <-  yield_int %>% 
  st_join(terrain_v,
          join = st_equals,
          left = T) %>% 
  st_join(eca_v,
          join = st_equals,
          left = T) %>% 
  relocate(geometry, .after = last_col())

all_v
```
# Exporting all Data
```{r}
write_sf(all_v,
         "../Output/all_v.geojson")
```


#EDA
```{r}
summary(all_v)
```
# Map 

```{r Yield Map}
yield_map <- ggplot() +
  geom_sf(data = all_v,
          aes(fill = ipyield_lbac),
          color = NA) +
  scale_fill_viridis_b() +
  geom_sf(data = boundary,
          fill = NA) +
  mytheme_map

yield_map
```
```{r Elevation Map}
elev_map <-  ggplot()+
  geom_sf(data = all_v,
          aes(fill = elev_m),
          color = NA) +
  scale_fill_viridis_b() +
  geom_sf(data = boundary,
          fill = NA) +
  mytheme_map

elev_map
```
```{r Slope Map}
slope_map <- ggplot()+
  geom_sf(data  = all_v,
          aes(fill = slope),
          color = NA) +
  scale_fill_viridis_b() +
  geom_sf(data = boundary,
          fill = NA)+
  mytheme_map

slope_map
```
```{r Aspect Map}
aspect_map <-  ggplot() +
  geom_sf(data = all_v,
          aes(fill = aspect),
          color = NA) +
  scale_fill_viridis_b()+
  geom_sf(data = boundary,
          fill = NA) +
  mytheme_map

aspect_map
```



```{r Shallow ECa Map}
sh_eca_map <- ggplot() +
  geom_sf(data = all_v,
          aes(fill = shallow_eca),
          color = NA) +
  scale_fill_viridis_b() +
  geom_sf(data = boundary,
          fill = NA)+
  mytheme_map

sh_eca_map
```
```{r Deep ECa Map}
dp_eca_map <- ggplot() +
  geom_sf(data = all_v,
          aes(fill = deep_eca),
          color = NA) +
  scale_fill_viridis_b() +
  geom_sf(data = boundary,
          fill = NA)+
  mytheme_map

dp_eca_map
```

```{r All Maps}
(yield_map + sh_eca_map + dp_eca_map) /
  (elev_map + slope_map + aspect_map)

ggsave("../Output/allmaps.png",
       width = 10,
       height = 5
       )
```


#Validation

```{r boxplot}
all_v %>% 
  mutate()
```

