---
title: "Terrain"
author: "Sandesh Shrestha"
format: html
editor: visual
---

#Setup
```{r Setup, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(janitor)
library(readr)
library(sf) #vector manipulation
library(ggplot2)
library(viridis)
library(ggthemes)
library(gstat) #IDW
library(stars) #raster manipulation
library(terra) #topographical variables
library(patchwork) #combining multiple plots  
library(tibble) #rownames to column
```

```{r reading elevation data}
mytheme_map <- theme_map() +
  theme(legend.position = "right",
        panel.background = element_rect(fill = "white",
                                        color = NA),
        plot.background = element_rect(fill = "white",
                                       color = NA),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)
        )
```

# Reading Data
```{r}
elev <- read.csv("../Data/Deer Run1 Elevation.csv")

elev
```
```{r boundary}
boundary <- read_sf("../Data/boundary/DR1 boundary.shp") %>%
  st_transform(crs = 6345)

boundary
```

# Wrangling
```{r elev_w}
elev_w <- elev %>% 
  clean_names() %>% 
  rename(elev_ft = elevation) %>% 
  mutate(elev_m = elev_ft * 0.3048) %>% 
  st_as_sf(coords = c("longitude", "latitude")) %>% 
  st_set_crs(value = 4326) %>% 
  st_transform(crs = 6345)

elev_w
```
```{r Summary}
summary(elev_w)
```

# EDA
```{r elev_w Map}
elev_w %>% 
  ggplot() +
  geom_sf(aes(color = elev_m),
          size =.1) +
  scale_color_viridis_c(option = "E") +
  mytheme_map
```
# Interpolation of Elevation
```{r Grid_r}
grid_r <- boundary %>% 
  st_make_grid(cellsize = 10) %>% 
  st_as_sf() %>% 
  st_rasterize(dx = 10) %>% 
  st_crop(boundary)

grid_r

ggplot() +
  geom_stars(data = grid_r) +
  theme_void()
```
```{r idw_mod}
idw_mod <- gstat(formula = elev_m ~ 1,
                 data = elev_w)

idw_mod
```
```{r}
idw_pred <- predict(idw_mod,
                    grid_r)

idw_pred
```

# Elevation Map
```{r}
elev_map <- ggplot() +
  geom_stars(data = idw_pred) +
  geom_sf(data = boundary, 
          fill = NA,
          size = 10) +
  scale_fill_viridis_b(breaks = c(56,57, 58, 59, 60, 61, 62, 63, 64, 65)) +
  labs(fill = "Elev\n(m)") +
  mytheme_map

elev_map
```

# Computing Secondary Varibales
## Slope
```{r}
slope <- idw_pred %>% 
  dplyr::select(elev_m = var1.pred) %>% 
                  terra::rast() %>% 
                  terra::terrain("slope",
                                 unit = "radians"
                                 ) %>%
                  st_as_stars() %>% 
                  st_set_crs(value = 6345) %>% 
                  mutate(pct = tan(slope) * 100) %>%
                  dplyr::select(pct)
                  

slope
```
### Slope Map
```{r}
slope_map <- ggplot() +
  geom_stars(data = slope) +
  geom_sf(data = boundary,
          fill = NA) +
  scale_fill_viridis_b() +
  labs(fill = "slope\n(%)")+
  mytheme_map +
  theme(legend.position = "right")

slope_map
```
## Aspect
```{r aspect}
aspect <- idw_pred %>% 
  dplyr::select(elev_m = var1.pred) %>%
  terra::rast() %>%
  terra::terrain("aspect",
                 unit = "degrees") %>%
  st_as_stars() %>%
  st_set_crs(value = 6345)
aspect
```
### Aspect Map
```{r}
aspect_map <- ggplot() +
  geom_stars(data = aspect) +
  geom_sf(data = boundary,
          fill = NA) +
  scale_fill_viridis_b(breaks = c(22.5,
                                  67.5,
                                  112.5,
                                  157.5,
                                  202.5,
                                  247.5,
                                  292.5,
                                  337.5)) +
  labs(fill = "Aspect\n(degrees)")+
  mytheme_map+
  theme(legend.position = "right")

aspect_map
```
## Flow Direction
```{r flowdir}
flowdir <- idw_pred %>% 
  dplyr::select(elev_m = var1.pred) %>%
  terra::rast() %>% 
  terra::terrain("flowdir",
                 unit = "radians") %>% 
  st_as_stars() %>% 
  st_set_crs(value = 6345)

flowdir
```
### Flow direction Map
```{r}
flowdir_map <- ggplot() +
  geom_stars(data = flowdir) +
  geom_sf(data = boundary,
          fill = NA)+
  scale_fill_viridis_b(
                       breaks = c(1, 2,
                                  4, 8,
                                  16, 32,
                                  64, 128)) +
  labs(fill = "Flow dir.") +
  mytheme_map

flowdir_map
```
```{r flowdir map 2}
ggplot() +
  geom_stars(data = flowdir %>%
  mutate(flowdir = factor(flowdir))) +
  geom_sf(data = boundary,
          fill = NA) +
  scale_fill_discrete() +
  labs(fill = "Flow Dir.") +
  mytheme_map
```
```{r}
ggplot() +
  geom_stars(data = flowdir %>%
  mutate(flowdir = factor(flowdir))
) +
  geom_sf(data = boundary, fill = NA) +
  scale_fill_discrete()+
  labs(fill = "Flow Dir.")+
  mytheme_map+
  facet_wrap(~flowdir)+
  theme(legend.position = "none")
```
## Plotting all together
```{r}
elev_map + slope_map + aspect_map + flowdir_map
ggsave("../Output/terrain.png",
       width = 10,
       height = 6)
```

# Grid Extraction
```{r}
#Elevation
elev_v <- idw_pred %>% 
  st_as_sf(as_points = F,
           merge = F) %>% 
  dplyr::select(elev_m = var1.pred)
elev_v

#Slope
slope_v <- slope %>%
  st_as_sf(as_points = F,
           merge = F
           ) %>%
  dplyr::select(slope = pct)
slope_v

#Aspect
aspect_v <- aspect %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(aspect) 
aspect_v

#FLowdir
flowdir_v <- flowdir %>%
  st_as_sf(as_points = F, 
           merge = F) %>%
  dplyr::select(flowdir) 
flowdir_v
```
# Joining all topo variables in one object
```{r terrain_v}
terrain_v <- elev_v %>%
  st_join(slope_v,
          join = st_equals,
          left = T)%>%
  st_join(aspect_v,
          join = st_equals,
          left = T)%>%
  st_join(flowdir_v,
          join = st_equals,
          left = T)


terrain_v
```
# Exporting
```{r}
write_sf(terrain_v,
         "../Output//terrain_v.geojson",
         delete_dsn = T)
```

